# Generated by Django 4.1 on 2022-08-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_account'),
        ('questions', '0002_questionanswered_selectedchoice'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_left', models.DurationField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_taken', to='applicants.applicant')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('question_answered', models.ManyToManyField(related_name='assessment_taken', to='questions.questionanswered')),
                ('selected_choice', models.ManyToManyField(related_name='assessment_taken', to='questions.selectedchoice')),
            ],
        ),
    ]
