# Generated by Django 4.1 on 2022-08-29 07:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assessment',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
