# Generated by Django 4.1 on 2022-08-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={},
        ),
    ]
