# Generated by Django 4.1 on 2022-08-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': (('can_view_all', 'View all pages'),)},
        ),
    ]
