# Generated by Django 4.1 on 2022-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
