# Generated by Django 4.1 on 2022-08-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_view_all', 'View all pages'),)},
        ),
    ]
