# Generated by Django 4.1 on 2022-08-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
